@startuml Space_Invaders
class Juego{
- iniciarJuego
- finalzarJuego
}
class Jugador{
- moverTanque
- puntaje
}
class IA{
- atacarJugador
- moverse
* izquierda
* derecha
}
class Muro{
- proteger
}
class Tanque{  
- misparar
- atacar
- moverse
*izquierda
*derecha
}
class NavesEnemigas{
-atacarJugador
}
class Misil{
-destruirEnemigo
-destruirJugador
}
class Colisionable 
class Boton{
-Disparar
}
class PlatilloEnemigo{
-Moverse
*Izquierda
*Derecha
}
class PalancaMovimiento{
    -Moverse
*Izquierda
*Derecha
}
class MapaEspacio{
    -personajesVolando
}

Jugador o-- Tanque
Muro --|> Colisionable
Misil --|> Colisionable
IA o-- NavesEnemigas
NavesEnemigas o-- Misil
Boton --|> Misil
Tanque *--  Misil
Jugador o-- Boton
NavesEnemigas --|> Colisionable
Tanque --|> Colisionable
PlatilloEnemigo --|> Colisionable
Tanque o-- Misil
NavesEnemigas *--  Misil
PlatilloEnemigo --|> IA
Jugador o-- PalancaMovimiento
Juego *-- MapaEspacio
@enduml