@startuml Space_Invaders
class Juego{
- iniciarJuego
- finJuego
}
class Jugador{
- moverTanque
- 
}
class IA{
- atacarJugador
- moverse
* izquierda
* derecha
}
class Muro{
- proteger
}
class Tanque{
- misparar
- atacar
- moverse
*izquierda
*derecha
}
class Enemigo{
-atacarJugador
}
class Misil{
-destruirEnemigo
-destruirJugador
}
class Colisionable 
class Boton{
-Disparar
}
class PlatilloEnemigo{
-Moverse
*Izquierda
*Derecha
}

Jugador o-- Tanque
Muro --|> Colisionable
Misil --|> Colisionable
IA o-- Enemigo
Enemigo o-- Misil
Boton --|> Misil
Tanque *--  Misil
Jugador o-- Boton
Enemigo --|> Colisionable
Tanque --|> Colisionable
PlatilloEnemigo --|> Colisionable
Tanque o-- Misil
Enemigo *--  Misil
@enduml